[project]
channels = ["conda-forge"]
name = "tprstats"
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64", "linux-aarch64"]

[dependencies]
statsmodels = ">=0.14.4,<0.15"
pandas = ">=2.2.3,<3"
matplotlib = ">=3.9.2,<4"

[host-dependencies]
pip = "*"
hatchling = "*"

[pypi-dependencies]
tprstats = { path = ".", editable = true }

[feature.dev.dependencies]
ruff = ">=0.5.6"
pre-commit = ">=3"
pytest = ">=7.1.2"
pytest-xdist = ">=2.5.0"
openpyxl = ">=3.1.5,<4"
ipykernel = ">=6.29.5,<7"
pip = ">=24.3.1,<25"

[feature.release.dependencies]
hatch = ">=1.12.0"
twine = ">=5.1.1"

[feature.release.tasks]
build = "hatch build"

[feature.docs.dependencies]
Sphinx = ">=7.3.7"
furo = ">=2023.5.20"
sphinxcontrib-apidoc = ">=0.3.0"
myst-parser = ">=2.0.0"
[feature.docs.tasks]
docs = "cd docs && make html "
readthedocs = "rm -rf $READTHEDOCS_OUTPUT/html && cp -r docs/build/html $READTHEDOCS_OUTPUT/html"

[feature.py310.dependencies]
python = "3.10.*"
[feature.py311.dependencies]
python = "3.11.*"
[feature.py312.dependencies]
python = "3.12.*"

[tasks]
postinstall = "pip install --no-build-isolation --no-deps --disable-pip-version-check -e ."
lint = "ruff check --fix src/tprstats"
format = "ruff format src/tprstats"

[environments]
default = ["py312", "dev"]
py310 = ["py310", "dev"]
py311 = ["py311", "dev"]
py312 = ["py312", "dev"]
docs = ["docs"]
release = { features = ["release"], no-default-feature = true }
