[tool.poetry]
name = "tprstats"
version = "0.1.0"
description = "Statistical recipes, methods and applications for students at the Tepper School of Business."
authors = ["Stephen Epple"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
